New Guide for Spring Cloud Stream
spring-guides/gs-spring-cloud-stream pull request #5
Opened 2023-01-17 20:48 UTC by robertmcnees

I noticed that our guide for Spring Cloud Stream lacked any code samples and only pointed to other documentation.  I added 3 new applications and documentation to walk a user through using various functionality for Spring Cloud Stream.

2023-01-20 17:41 UTC, robertmcnees commented
Addresses #6

2023-01-26 16:53 UTC, Buzzardo requested changes

2023-01-26 16:53 UTC, Buzzardo commented on README.adoc
> +In this guide, we will demonstrate the capability of Spring Cloud Stream.  We will create 3 applications to showcase the different
Change to:

This guide demonstrates the capability of Spring Cloud Stream.  We create three applications to showcase the different

2023-01-26 16:53 UTC, Buzzardo commented on README.adoc
> +- name-source : publish a String at a regular interval to initiate the stream.  For this example, publish a name as a String.
Remove the space before the colon. Capitalize the word after the colon. Use only one space before a period.

This comment applies to all the items in this list.

2023-01-26 16:53 UTC, Buzzardo commented on README.adoc
> +- name-sink : consume the results from name-processor and perform an action.  In this case, print out the results to standard out.
Remove "out" from "print out". It's unnecessary.

2023-01-26 16:53 UTC, Buzzardo commented on README.adoc
> +For this example the names of the applications follow the Spring Cloud Stream concepts (`Source`, `Processor`, `Sink`).  These concepts map
Add a comma after "example". Use only one space after a period.

2023-01-26 16:53 UTC, Buzzardo commented on README.adoc
> +to the logical equivalent of the Java 8 functions (`Supplier`, Function, Consumer respectively).
Add a comma before "respectively".

2023-01-26 16:53 UTC, Buzzardo commented on README.adoc
> +While Spring Cloud Stream can support a Function(s) in a Source  as well as Sink via function composition, we will have 3 separate applications to demonstrate how each can work as an independent appl
Change to: 

While Spring Cloud Stream can support one or more Function instances in a Source  as well as in a Sink (via function composition), we have three separate applications to demonstrate how each can work as an independent application.

2023-01-26 16:53 UTC, Buzzardo commented on README.adoc
> +In this guide, we will work from the back to the front.  That is, we will first build the Sink application, followed by the Processor, and
Remove all instances of "will". Use only one space after a period.

2023-01-26 16:53 UTC, Buzzardo commented on README.adoc
> +finally build the Source.  We will use the RabbitMQ dashboard UI to test each component as we go.
Use only one space after a period.

2023-01-26 16:53 UTC, Buzzardo commented on README.adoc
> +In order to use Spring Cloud Stream functionality, we need to ensure that a message broker is accessible.  For this guide we will use RabbitMQ.
Change to:

To use Spring Cloud Stream functionality, we need to ensure that a message broker is accessible.  For this guide, we use RabbitMQ.

2023-01-26 16:53 UTC, Buzzardo commented on README.adoc
> +If a local Docker environment is found, the following command can start RabbitMQ
Add a colon at the end of this line.

2023-01-26 16:53 UTC, Buzzardo commented on README.adoc
> +The result is that RabbitMQ should be link:http://localhost:15672/[accessible locally] with the username/password of guest/guest.
Mark "guest/guest" as code (because the reader needs to type exactly those values).

2023-01-26 16:53 UTC, Buzzardo commented on README.adoc
> +The sink (`java.util.function.Consumer`) is defined in `NameSinkConfiguration` as
Add a colon at the end of this line.

2023-01-26 16:53 UTC, Buzzardo commented on README.adoc
> +We want to customize this so that we can later hook our processor to our sink.
Add "exchange" after "this".

2023-01-26 16:53 UTC, Buzzardo commented on README.adoc
> +Starting this application without configuring the exchange name will automatically generate an exchange in RabbitMQ titled `nameSink-in-0`.
Change to:

Starting this application without configuring the exchange name automatically generates an exchange named `nameSink-in-0` in RabbitMQ.

2023-01-26 16:53 UTC, Buzzardo commented on README.adoc
> +To test the sink we will manually publish a JSON message representing a `Person` record to the newly generated exchange:
Add a comma after "To test the sink". Remove "will".

2023-01-26 16:53 UTC, Buzzardo commented on README.adoc
> +And in our application logs we should see the data outputted:
Change "And" to "Also," (including the comma).

(It's not strictly ungrammatical to start a sentence with a preposition - people do it all the time. However, technical documentation is formal, so we avoid that.)

2023-01-26 16:53 UTC, Buzzardo commented on README.adoc
> +The processor (`java.util.function.Function`) is defined in `NameProcessorConfiguration` as
Add a colon to the end of the line.

2023-01-26 16:53 UTC, Buzzardo commented on README.adoc
> +This function will take a String value as input and create a new Person record that adds the timestamp of when the data was processed.
Change "will take" to "takes" and "create" to "creates." (In other words, remove "will".)

2023-01-26 16:53 UTC, Buzzardo commented on README.adoc
> +Running this application will create 2 new exchanges in RabbitMQ: `processName-in-0` and `processName-out-0`.
Change "will create 2" to "creates two".

2023-01-26 16:53 UTC, Buzzardo commented on README.adoc
> +sink and soon to the supplier.
Add commas around "soon".

2023-01-26 16:53 UTC, Buzzardo commented on README.adoc
> +Using the RabbitMQ dashboard, we will now send a String (name) to the processor input exchange and watch as it flows to the connected sink.
Change "will" to "can".

2023-01-26 16:53 UTC, Buzzardo commented on README.adoc
> +If the processor and the sink are connected properly, you should still the output from your running sink:
Change "still" to "see".

2023-01-26 16:53 UTC, Buzzardo commented on README.adoc
> +The Source (`java.util.function.Supplier`) is defined in `NameSourceConfiguration` as
Add a colon to the end of the line.

2023-01-26 16:53 UTC, Buzzardo commented on README.adoc
> +NOTE: The output of the source should matches the input of the processor
Change "matches" to "match" and add a period at the end.

2023-01-26 16:53 UTC, Buzzardo commented on README.adoc
> +If `name-processor` and `name-sink` are already running, starting the `name-source` will immediately start messages flowing through the system.
Change "will immediately start" to "immediately starts". (In other words, remove "will".

2023-01-26 16:53 UTC, Buzzardo commented on README.adoc
> +You should see the same name continuously outputted by `name-sink` with a slightly different timestamp for when the message
Change "outputted" to "produced".

(The past tense of "output" is "output", but I suggest avoiding the whole issue by using a different word.

2023-01-27 16:32 UTC, Buzzardo approved these changes

2023-01-27 16:32 UTC, merged